---
abstract: 'Allows non-relative dates to be displayed as Discordian'
author:
  - 'Kevin Falcone <falcone@bestpractical.com>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.78'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-DateDiscordian
no_index:
  directory:
    - inc
    - t
requires:
  Date::Discordian: 0
version: 0.01
